cache: &cache
  key: "$CI_COMMIT_SHA"
  paths:
    - output/**/filesystem/*.tar.gz
    - output/**/filesystem/.stamp*

stages:
  - prepare
  - minimal
  - base

.image:
  script:
    - JOB_NAME=( $CI_JOB_NAME )
    - BOARD=${JOB_NAME[0]}
    - VARIANT=${JOB_NAME[1]}
    - RELEASE=${JOB_NAME[2]}
    - python3 -m olimage $ARGS -v image $BOARD $RELEASE $VARIANT $BOARD-$RELEASE-$VARIANT-$DATE.img
    - mv -vf output/*/images/$BOARD-$RELEASE-$VARIANT-$DATE.img* /output/
  tags:
    - olimage

prepare:
  allow_failure: false
  script:
    - echo "Starting build..."
    - echo "DATE=$(date +%Y%m%d-%H%M%S)" >> build.env
    - python3 -m olimage clean
  stage: prepare
  tags:
    - olimage
  artifacts:
    reports:
      dotenv: build.env
  when: manual

A20-OLinuXino minimal buster:
  extends: .image
  stage: minimal

A20-OLinuXino base buster:
  stage: base
  extends: .image
  needs:
    - "A20-OLinuXino minimal buster"
  cache:
    <<: *cache
    policy: pull

A20-OLinuXino minimal bionic:
  stage: minimal
  extends: .image

A20-OLinuXino base bionic:
  stage: base
  extends: .image
  needs:
    - "A20-OLinuXino minimal bionic"
  cache:
    <<: *cache
    policy: pull

A20-OLinuXino minimal focal:
  stage: minimal
  extends: .image

A20-OLinuXino base focal:
  extends: .image
  stage: base
  needs:
    - "A20-OLinuXino minimal focal"
  cache:
    <<: *cache
    policy: pull

A13-OLinuXino minimal buster:
  stage: minimal
  extends: .image

A13-OLinuXino base buster:
  stage: base
  extends: .image
  needs:
    - "A13-OLinuXino minimal buster"
  cache:
    <<: *cache
    policy: pull

A13-OLinuXino minimal bionic:
  stage: minimal
  extends: .image

A13-OLinuXino base bionic:
  stage: base
  extends: .image
  needs:
    - "A13-OLinuXino minimal bionic"
  cache:
    <<: *cache
    policy: pull

A64-OLinuXino minimal buster:
  stage: minimal
  extends: .image

A64-OLinuXino base buster:
  stage: base
  extends: .image
  needs:
    - "A64-OLinuXino minimal buster"
  cache:
    <<: *cache
    policy: pull

A64-OLinuXino minimal bionic:
  stage: minimal
  extends: .image

A64-OLinuXino base bionic:
  stage: base
  extends: .image
  needs:
    - "A64-OLinuXino minimal bionic"
  cache:
    <<: *cache
    policy: pull

A64-OLinuXino minimal focal:
  stage: minimal
  extends: .image

A64-OLinuXino base focal:
  stage: base
  extends: .image
  needs:
    - "A64-OLinuXino minimal focal"
  cache:
    <<: *cache
    policy: pull

A10-OLinuXino minimal buster:
  stage: minimal
  extends: .image

A10-OLinuXino base buster:
  stage: base
  extends: .image
  needs:
    - "A10-OLinuXino minimal buster"
  cache:
    <<: *cache
    policy: pull

A10-OLinuXino minimal bionic:
  stage: minimal
  extends: .image

A10-OLinuXino base bionic:
  stage: base
  extends: .image
  needs:
    - "A10-OLinuXino minimal bionic"
  cache:
    <<: *cache
    policy: pull
