stages:
  - minimal

minimal:buster:
  artifacts:
    paths:
      - result/*
  before_script:
    - apt-get update
    - apt-get install -y p7zip-full uuid-runtime
  script:
    - python3 -m olimage -v image A20-OLinuXino-Lime buster minimal $(uuidgen).img
    - mkdir result
    - 7z -a result/minimal.7z output/images/*.img
  stage: minimal
  tags:
    - olimage
  when: manual