cache: &cache
  key: "$CI_COMMIT_SHA"
  paths:
    - output/**/filesystem/*.tar.gz
    - output/**/filesystem/.stamp*

stages:
  - prepare
  - minimal
  - base

.image: &image
  script:
    - JOB_NAME=( $CI_JOB_NAME )
    - BOARD=${JOB_NAME[0]}
    - VARIANT=${JOB_NAME[1]}
    - RELEASE=${JOB_NAME[2]}
    - echo "DATE=$DATE" >> build.env
    - python3 -m olimage $ARGS -v image $BOARD $RELEASE $VARIANT $BOARD-$RELEASE-$VARIANT-$DATE.img
    - mv -vf output/*/images/$BOARD-$RELEASE-$VARIANT-$DATE.img* /output/
  tags:
    - olimage
  artifacts:
    reports:
      dotenv: build.env

.base: &base
  <<: *image
  cache:
    <<: *cache
    policy: pull

prepare:
  allow_failure: false
  script:
    - echo "Starting build..."
    - echo "DATE=$(date +%Y%m%d-%H%M%S)" >> build.env
    - python3 -m olimage clean
  stage: prepare
  tags:
    - olimage
  artifacts:
    reports:
      dotenv: build.env
  when: manual

A20-OLinuXino minimal buster:
  stage: minimal
  <<: *image

A20-OLinuXino base buster:
  stage: base
  <<: *base
  needs:
    - "A20-OLinuXino minimal buster"

A20-OLinuXino minimal focal:
  stage: minimal
  <<: *image

A20-OLinuXino base focal:
  stage: base
  <<: *base
  needs:
    - "A20-OLinuXino minimal focal"

A13-OLinuXino minimal buster:
  stage: minimal
  <<: *image

A13-OLinuXino base buster:
  stage: base
  <<: *base
  needs:
    - "A13-OLinuXino minimal buster"

A13-OLinuXino minimal focal:
  stage: minimal
  <<: *image

A13-OLinuXino base focal:
  stage: base
  <<: *base
  needs:
    - "A13-OLinuXino minimal focal"

A64-OLinuXino minimal buster:
  stage: minimal
  <<: *image

A64-OLinuXino base buster:
  stage: base
  <<: *base
  needs:
    - "A64-OLinuXino minimal buster"

A64-OLinuXino minimal focal:
  stage: minimal
  <<: *image

A64-OLinuXino base focal:
  stage: base
  <<: *base
  needs:
    - "A64-OLinuXino minimal focal"

A10-OLinuXino minimal buster:
  stage: minimal
  <<: *image

A10-OLinuXino base buster:
  stage: base
  <<: *base
  needs:
    - "A10-OLinuXino minimal buster"

A10-OLinuXino minimal focal:
  stage: minimal
  <<: *image

A10-OLinuXino base focal:
  stage: base
  <<: *base
  needs:
    - "A10-OLinuXino minimal focal"

STM32MP1-OLinuXino minimal buster:
  stage: minimal
  <<: *image
  when: manual

STM32MP1-OLinuXino minimal focal:
  stage: minimal
  <<: *image
  when: manual
