cache: &cache
    key: "$CI_COMMIT_SHA"
    paths:
      - output/**/filesystem/*.tar.gz
      - output/**/filesystem/.stamp*

stages:
  - prepare
  - minimal
  - base

.image:
  script:
    - python3 -m olimage -v image $OLIMAGE_BOARD $OLIMAGE_RELEASE $OLIMAGE_VARIANT $OLIMAGE_BOARD-$OLIMAGE_RELEASE-$OLIMAGE_VARIANT-$(date +%Y%m%d-%H%M%S).img
    - mv -vf output/*/images/$OLIMAGE_BOARD-$OLIMAGE_RELEASE-$OLIMAGE_VARIANT-*.img* /output/
  tags:
    - olimage

prepare:
  allow_failure: false
  script:
    - echo "Starting build..."
    - python3 -m olimage clean
  stage: prepare
  tags:
    - olimage
  when: manual

A20:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A20:base:buster:
  extends: .image
  needs:
    - "A20:minimal:buster"
  stage: base
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

A20:minimal:bionic:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: minimal

A20:base:bionic:
  extends: .image
  needs:
    - "A20:minimal:bionic"
  stage: base
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

A13:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A13-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A13:base:buster:
  extends: .image
  needs:
    - "A13:minimal:buster"
  stage: base
  variables:
    OLIMAGE_BOARD: A13-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

A13:minimal:bionic:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A13-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: minimal

A13:base:bionic:
  extends: .image
  needs:
    - "A13:minimal:bionic"
  stage: base
  variables:
    OLIMAGE_BOARD: A13-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

A64:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A64:base:buster:
  extends: .image
  needs:
    - "A64:minimal:buster"
  stage: base
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

A64:minimal:bionic:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: minimal

A64:base:bionic:
  extends: .image
  needs:
    - "A64:minimal:bionic"
  stage: base
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

A10:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A10-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A10:base:buster:
  extends: .image
  needs:
    - "A10:minimal:buster"
  stage: base
  variables:
    OLIMAGE_BOARD: A10-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

A10:minimal:bionic:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A10-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: minimal

A10:base:bionic:
  extends: .image
  needs:
    - "A10:minimal:bionic"
  stage: base
  variables:
    OLIMAGE_BOARD: A10-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: base
  cache:
    <<: *cache
    policy: pull

