stages:
#  - clean
  - minimal
  - lite
  - base

.image:
  allow_failure: false
  script:
    # Announce build
    - echo "Building $OLIMAGE_VARIANT image for $OLIMAGE_BOARD based on $OLIMAGE_RELEASE as $OLIMAGE_IMAGE."

    # Run the build
    - python3 -m olimage -v --output=/output image $OLIMAGE_BOARD $OLIMAGE_RELEASE $OLIMAGE_VARIANT $OLIMAGE_IMAGE

    # Archive the
#    - 7z a /output/images/$OLIMAGE_IMAGE.7z /output/images/$OLIMAGE_IMAGE
  tags:
    - olimage
  when: manual

#clean:
#  allow_failure: false
#  script:
#    - python3 -m olimage -v --output=/output clean
#  stage: clean
#  tags:
#    - olimage
#  when: manual

A20:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_IMAGE: A20-OLinuXino_minimal_buster.img
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A20:lite:buster:
  extends: .image
  needs: ["A20:minimal:buster"]
  stage: lite
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_IMAGE: A20-OLinuXino_lite_buster.img
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: lite

A20:base:buster:
  extends: .image
  needs: ["A20:lite:buster"]
  stage: base
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_IMAGE: A20-OLinuXino_base_buster.img
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: base
