stages:
  - prepare
  - minimal
  - lite
  - base

.image:
  script:
    - python3 -m olimage -v --output=/output image $OLIMAGE_BOARD $OLIMAGE_RELEASE $OLIMAGE_VARIANT $OLIMAGE_BOARD-$OLIMAGE_VARIANT-$OLIMAGE_RELEASE-$(date +%Y%m%d-%H%M%S).img
  tags:
    - olimage

run:
  script:
    - echo "Starting without cleaning"
  stage: prepare
  tags:
    - olimage
  when: manual
clean:
  allow_failure: false
  script:
    - echo "Cleaning old files"
    - python3 -m olimage -v --output=/output clean
  stage: prepare
  tags:
    - olimage
  when: manual

A20:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A20:lite:buster:
  extends: .image
  needs:
    - "A20:minimal:buster"
  stage: lite
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: lite

A20:base:buster:
  extends: .image
  needs:
    - "A20:minimal:buster"
    - "A20:lite:buster"
  stage: base
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: base

A20:minimal:bionic:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: minimal

A20:lite:bionic:
  extends: .image
  needs:
    - "A20:minimal:bionic"
  stage: lite
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: lite

A20:base:bionic:
  extends: .image
  needs:
    - "A20:minimal:bionic"
    - "A20:lite:bionic"
  stage: base
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: base

A64:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A64:lite:buster:
  extends: .image
  needs:
    - "A64:minimal:buster"
  stage: lite
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: lite

A64:base:buster:
  extends: .image
  needs:
    - "A64:minimal:buster"
    - "A64:lite:buster"
  stage: base
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: base

A64:minimal:bionic:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: minimal

A64:lite:bionic:
  extends: .image
  needs:
    - "A64:minimal:bionic"
  stage: lite
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: lite

A64:base:bionic:
  extends: .image
  needs:
    - "A64:minimal:bionic"
    - "A64:lite:bionic"
  stage: base
  variables:
    OLIMAGE_BOARD: A64-OLinuXino
    OLIMAGE_RELEASE: bionic
    OLIMAGE_VARIANT: base
