stages:
  - minimal
  - lite

.image:
  allow_failure: false
  artifacts:
    paths:
      - output/*
  script:
    - echo "Building $OLIMAGE_VARIANT image for $OLIMAGE_BOARD based on $OLIMAGE_RELEASE as $OLIMAGE_IMAGE."
    - python3 -m olimage -v image $OLIMAGE_BOARD $OLIMAGE_RELEASE $OLIMAGE_VARIANT $OLIMAGE_IMAGE
    - 7z a output/images/$OLIMAGE_IMAGE.7z output/images/$OLIMAGE_IMAGE
    - find output/filesystem/ -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;
  tags:
    - olimage
  when: manual

A20:minimal:buster:
  extends: .image
  stage: minimal
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_IMAGE: A20-OLinuXino_minimal_buster.img
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal

A20:lite:buster:
  extends: .image
  needs:
    - job: "A20:minimal:buster"
      artifacts: true
  stage: lite
  variables:
    OLIMAGE_BOARD: A20-OLinuXino
    OLIMAGE_IMAGE: A20-OLinuXino_lite_buster.img
    OLIMAGE_RELEASE: buster
    OLIMAGE_VARIANT: minimal
