version: '3'

services:
  apt-cacher-ng:
    restart: unless-stopped
    image: sameersbn/apt-cacher-ng:latest
    ports:
    - "31420:3142"
    volumes:
    - ./apt-cacher-ng:/var/cache/apt-cacher-ng
