u-boot:
  Package: 'u-boot-sunxi'
  Version: ~
  Architecture: ~
  Maintainer: 'Olimex Dev team <support@olimex.com>'
  Installed-Size: ~
  Recommends: 'arm-trusted-firmware, u-boot-tools'
  Breaks: 'u-boot (<< 2014.10~rc2+dfsg1-2~), u-boot-sunxi'
  Replaces: 'u-boot (<< 2014.10~rc2+dfsg1-2~), u-boot-sunxi'
  Provides: 'u-boot-sunxi'
  Section: 'admin'
  Priority: 'optional'
  Multi-Arch: 'same'
  Homepage: 'http://www.denx.de/wiki/U-Boot/'
  Description: 'A boot loader for sunxi systems\n
   Das U-Boot is a cross-platform bootloader for embedded systems,\n
   used as the default boot loader by several board vendors.  It is\n
   intended to be easy to port and to debug, and runs on many\n
   supported architectures, including PPC, ARM, MIPS, x86, m68k,\n
   NIOS, and Microblaze.\n
   .\n
   This package includes boot loaders for various Allwinner/sunxi\n
   platforms.\n
   .\n
   Included platforms:\n
   a64-olinuxino'
