boards:
  # Define boards architecture
  arch: 'armhf'
  default: 'A10-OLinuXino-LIME'

  # Define load addresses
  loading:
    kernel:   '0x40080000'
    uenv:     '0x44000000'  
    fdt:      '0x4FA00000'
    overlays: '0x4FA10000'
    ramdisk:  '0x4FE00000'
    fit:      '0x58000000'

  # Define board models
  models:
    A10-OLinuXino-LIME-e16Gs16M:
      id: 10663
      fdt: 'sun4i-a10-olinuxino-lime-emmc.dtb'
      overlays:
        - 'sun4i-a10-spi0.dtbo'
        - 'spi0-spiflash.dtbo'

    A10-OLinuXino-LIME-n8GB:
      id: 8950
      fdt: 'sun4i-a10-olinuxino-lime-emmc.dtb'
      overlays:
        - 'sun4i-a10-spi0.dtbo'
        - 'spi0-spiflash.dtbo'

    A10-OLinuXino-LIME:
      id: 4746
      fdt: 'sun4i-a10-olinuxino-lime.dtb'

  name: 'A10-OLinuXino'
  soc: 'sun4i-a10'
