boards:
  # Define boards architecture
  arch: 'armhf'
  default: 'A13-OLinuXino'

  # Define load addresses
  loading:
    kernel:   '0x40080000'
    uenv:     '0x44000000'  
    fdt:      '0x4FA00000'
    overlays: '0x4FA10000'
    ramdisk:  '0x4FE00000'
    fit:      '0x58000000'

  # Define board models
  models:
    A13-OLinuXino:
      id: 4432
      fdt: 'sun5i-a13-olinuxino.dtb'
      overlays:
        - 'sun5i-a13-spi2.dbo'
    
    A13-SOM-256:
      id: 4787
      fdt: 'sun5i-a13-som-256.dtb'

    A13-SOM-512:
      id: 4788
      fdt: 'sun5i-a13-som-512.dtb'

  name: 'A13-OLinuXino'
  soc: 'sun5i-a13'
