boards:
  arch: 'armhf'

  models:
    A20-OLinuXino-MICRO:
      id: 2323
      fdt: 'sun7i-a20-olinuxino-micro.dtb'
      overlays: ~

    A20-OLinuXino-LIME2:
      id: 7701
      fdt: 'sun7i-a20-olinuxino-lime2.dtb'
      overlays: ~

  soc: 'sun7i-a20'
