boards:
  arch: &arch 'arm64'

  board_packages:
    linux:
      arch: *arch
      defconfig: ~
      refs: 'v5.4-rc5'
      #source: 'https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable'
      source: 'https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux'
      targets:
        - 'Image'
        - 'dtbs'
        - 'modules'
      toolchain:
        prefix: 'aarch64-linux-gnu-'
        version: 7
      version: '5.4.0-rc5-1-olimex'
      localversion: '-1-olimex'

  bootloaders:
    spl:
      file: '/usr/lib/u-boot/a64-olinuxino/sunxi-spl.bin'
      block: 1024
      offset: 8
    u-boot:
      file: 'u-boot.itb'
      prepare:
        requires:
          - '/usr/lib/arm-trusted-firmware/sun50i_a64/bl31.bin'
          - '/usr/lib/u-boot/a64-olinuxino/sun50i-a64-olinuxino.dtb'
          - '/usr/lib/u-boot/a64-olinuxino/u-boot-nodtb.bin'
          - '/usr/lib/u-boot/a64-olinuxino/u-boot.bin'
          - '/usr/bin/mksunxi_fit_atf'
        commands:
          - '/usr/lib'
      block: 1024
      offset: 40

  family: 'sun50i-a64'

  # Define board variants
  variants:
    A64-OLinuXino-1Ge4GW:
      id : 8367
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'
      overlays: ~

    A64-OLinuXino-1G:
      id: 8857
      fdt: 'allwinner/sun50i-a64-olinuxino.dtb'
      overlays: ~

    A64-OLinuXino-2Ge8G-IND:
      id: 8861
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'
      overlays: ~

    A64-OLinuXino-1Gs16M:
      id: 9065
      fdt: 'allwinner/sun50i-a64-olinuxino.dtb'
      overlays:
        - 'spi0-spiflash.dtbo'

    A64-OLinuXino-1Ge16GW:
      id: 9849
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'
      overlays: ~
