boards:
  arch: 'arm64'
  default: 'A64-OLinuXino-1G'

  loading:
    kernel:   '0x40080000'
    uenv:     '0x44000000'
    fdt:      '0x4FA00000'
    overlays: '0x4FA10000'
    ramdisk:  '0x4FE00000'
    fit:      '0x58000000'

#  bootloaders:
#    spl:
#      file: '/usr/lib/u-boot/a64-olinuxino/sunxi-spl.bin'
#      block: 1024
#      offset: 8
#    u-boot:
#      file: 'u-boot.itb'
#      prepare:
#        requires:
#          - '/usr/lib/arm-trusted-firmware/sun50i_a64/bl31.bin'
#          - '/usr/lib/u-boot/a64-olinuxino/sun50i-a64-olinuxino.dtb'
#          - '/usr/lib/u-boot/a64-olinuxino/u-boot-nodtb.bin'
#          - '/usr/lib/u-boot/a64-olinuxino/u-boot.bin'
#          - '/usr/bin/mksunxi_fit_atf'
#        commands:
#          - '/usr/lib'
#      block: 1024
#      offset: 40
  # Define board variants
  models:
    A64-OLinuXino-1Ge4GW:
      id : 8367
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'

    A64-OLinuXino-1G:
      id: 8857
      fdt: 'allwinner/sun50i-a64-olinuxino.dtb'

    A64-OLinuXino-2Ge8G-IND:
      id: 8861
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'

    A64-OLinuXino-1Gs16M:
      id: 9065
      fdt: 'allwinner/sun50i-a64-olinuxino.dtb'
      overlays:
        - 'sun50i-a64-spi0.dtbo'
        - 'spi0-spiflash.dtbo'

    A64-OLinuXino-1Ge16GW:
      id: 9849
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'

  name: 'A64-OLinuXino'
  soc: 'sun50i-a64'
