boards:
  arch: &arch 'arm64'

  board_packages:
    arm-trusted-firmware:
      debug: true
      images:
        - 'build/sun50i_a64/debug/bl31.bin'
      platform: 'sun50i_a64'
      refs: 'v2.1'
      source: 'https://github.com/ARM-software/arm-trusted-firmware.git'
      targets:
        - 'bl31'
      toolchain: &toolchain
        prefix: 'aarch64-linux-gnu-'
        version: 7

    u-boot:
      arch: *arch
      defconfig: 'A64-OLinuXino'
      depends:
        - 'arm-trusted-firmware'
        - 'olimex-sunxi-overlays'
      install:
        - 'u-boot-sunxi-with-spl.bin:usr/lib/u-boot/a64-olinuxino/'
        - 'uboot.env.txt:usr/lib/u-boot/a64-olinuxino/'
        - 'uboot.env:boot/'
      refs: 'v2019.10'
      source: 'https://github.com/u-boot/u-boot.git'
      toolchain: *toolchain
      version: "+olimex-1"

    linux:
      arch: *arch
      depends:
        - 'u-boot'
      defconfig: ~
      refs: 'v5.4-rc5'
      #source: 'https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable'
      source: 'https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux'
      targets:
        - 'Image'
        - 'dtbs'
        - 'modules'
      toolchain: *toolchain
      version: '-1-olimex'

    olimex-sunxi-overlays:
      arch: 'all'
      refs: 'master'
      source: 'https://github.com/OLIMEX/OLIMEX-sunxi-overlays.git'

  bootloader:
    file: '/usr/lib/u-boot/a64-olinuxino/u-boot-sunxi-with-spl.bin'
    block: 512
    offset: 16

  family: 'sun50i-a64'

  # Define board variants
  variants:
    A64-OLinuXino-1Ge4GW:
      id : 8367
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'
      overlays: ~

    A64-OLinuXino-1G:
      id: 8857
      fdt: 'allwinner/sun50i-a64-olinuxino.dtb'
      overlays: ~

    A64-OLinuXino-2Ge8G-IND:
      id: 8861
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'
      overlays: ~

    A64-OLinuXino-1Gs16M:
      id: 9065
      fdt: 'allwinner/sun50i-a64-olinuxino.dtb'
      overlays:
        - 'sun50i-a64-spiflash.dtbo'

    A64-OLinuXino-1Ge16GW:
      id: 9849
      fdt: 'allwinner/sun50i-a64-olinuxino-emmc.dtb'
      overlays: ~
