boards:
  # Define boards architecture
  arch: 'armhf'
  default: 'STM32MP1xx-OLinuXino-LIME'

  # Define load addresses
  loading:
    kernel:   '0xc0000000'
    uenv:     '0xc1000000'
    fdt:      '0xc4000000'
    overlays: '0xc4200000'
    ramdisk:  '0xc4400000'
    fit:      '0xc2000000'

  # Define board models
  models:
    STM32MP1xx-OLinuXino-LIME:
      id: 1001
      fdt: 'stm32mp1xx-olinuxino-lime.dtb'

  name: 'STM32MP1-OLinuXino-LIME'
  soc: 'stm32mp1xx'
