version: '3'

services:
  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng:latest
    restart: unless-stopped
    volumes:
    - apt-cacher-ng:/var/cache/apt-cacher-ng

  nginx:
    command: [nginx-debug, '-g', 'daemon off;']
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - reprepro:/var/www/reprepro

  reprepro:
    build:
      context: ./docker/reprepro
    command: /ENTRYPOINT.sh
    depends_on:
      - nginx
    volumes:
      - reprepro:/var/reprepro/debian
      - ./docker/reprepro/ENTRYPOINT.sh:/ENTRYPOINT.sh
      - ./docker/reprepro/debian/conf:/var/reprepro/debian/conf:ro
      - ./docker/reprepro/keys:/var/reprepro/keys/
      - ./docker/reprepro/packages:/var/reprepro/packages

volumes:
  apt-cacher-ng:
  reprepro:

