distributions:
  debian:
    components: ['main', 'contrib', 'non-free']
    recommended: 'buster'
    releases:
      - 'buster'
    repository: 'http://httpredir.debian.org/debian'

  ubuntu:
    components: ['main', 'universe', 'multiverse']
    recommended: 'bionic'
    releases:
      - 'bionic'
      - 'focal'
    repository: 'http://ports.ubuntu.com/'
