.olimex: &olimex
  - olinuxino-overlays
  - u-boot-olinuxino
  - u-boot-tools-olinuxino
  - olinuxino-tools

# Release specific packages
releases:
  bionic:
    minimal:
      - linux-firmware
    base:
      - chromium-browser
  buster:
    minimal:
      - firmware-ralink
      - firmware-realtek
    base:
      - chromium

variants:
  minimal:
    description: "Minimal filesystem"
    packages:
      - bc
      - bzip2
      - chrony
      - cpufrequtils
      - crda
      - dbus
      - debconf-utils
      - device-tree-compiler
      - dialog
      - fake-hwclock
      - fping
      - htop
      - ifupdown
      - initramfs-tools
      - lsof
      - mmc-utils
      - mtd-utils
      - ncurses-term
      - netcat-openbsd
      - net-tools
      - network-manager
      - nocache
      - openssh-server
      - parted
      - psmisc
      - resolvconf
      - rsync
      - ssh
      - sudo
      - sysfsutils
      - sysstat
      - ucf
      - usbutils
      - wget
      - wireless-regdb
      - wireless-tools
      - *olimex

  lite:
    description: "Server-like filesystem"
    packages:
      - alsa-utils
      - aptitude
      - automake
      - avahi-autoipd
      - bash-completion
      - bison
      - bridge-utils
      - build-essential
      - curl
      - dnsutils
      - dosfstools
      - ethtool
      - evtest
      - expect
      - f2fs-tools
      - f3
      - fbset
      - flex
      - git
      - gnupg2
      - haveged
      - hdparm
      - html2text
      - ifenslave
      - iotop
      - iozone3
      - iperf3
      - iputils-arping
      - libdigest-sha-perl
      - libfuse2
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnss-myhostname
      - libpam-systemd
      - libproc-processtable-perl
      - libssl-dev
      - libwrap0-dev
      - man-db
      - networkd-dispatcher
      - ntfs-3g
      - pciutils
      - pv
      - python3-apt
      - qrencode
      - rfkill
      - screen
      - software-properties-common
      - stress
      - sunxi-tools
      - unattended-upgrades
      - unicode-data
      - unzip
      - vim
      - vlan

  base:
    description: "Desktop filesystem"
    packages:
      - apt-xapian-index
      - atril
      - cups
      - cups-pk-helper
      - dbus-x11
      - fbi
      - ffmpeg
      - galculator
      - gcr
      - geany
      - gnome-keyring
      - gnome-orca
      - gtk2-engines
      - gtk2-engines-murrine
      - gtk2-engines-pixbuf
      - gvfs-backends
      - gvfs-fuse
      - hexchat
      - hunspell-en-gb
      - hyphen-en-gb
      - libgck-1-0
      - libgl1-mesa-dri
      - libgtk2.0-bin
      - libpam-gnome-keyring
      - lightdm
      - lightdm-gtk-greeter
      - lxtask
      - mirage
      - mpv
      - network-manager-gnome
      - network-manager-openvpn-gnome
      - numix-gtk-theme
      - numix-icon-theme
      - onboard
      - p11-kit
      - paprefs
      - pasystray
      - pavucontrol
      - pavumeter
      - profile-sync-daemon
      - pulseaudio
      - synaptic
      - system-config-printer
      - system-config-printer-common
      - thunar-volman
      - tree
      - vlc
      - wamerican
      - wbritish
      - x11-xserver-utils
      - xarchiver
      - xfce4
      - xfce4-goodies
      - xfce4-notifyd
      - xfce4-power-manager
      - xfce4-screenshooter
      - xfce4-terminal
      - xfonts-base
      - xinit
      - xserver-xorg
      - xserver-xorg-video-fbdev

  full:
    packages:
      - avahi-daemon
      - kazam
      - libreoffice
      - libreoffice-style-tango
      - meld
      - remmina
      - thunderbird
      - transmission
