.olimex: &olimex
  - olinuxino-overlays
  - u-boot-olinuxino

releases:
  bionic:
    base:
      - chromium-browser
  buster:
    base:
      - chromium

services:
  olimage.core.setup.apt:
    packages:
      - apt-transport-https
      - ca-certificates
      - gnupg

  olimage.core.setup.console:
    packages:
      - console-setup
      - keyboard-configuration

  olimage.core.setup.locales:
    packages:
      - locales



variants:
  minimal:
    description: "Build minimal filesystem"
    packages:
      - bc
      - bzip2
      - chrony
      - cpufrequtils
      - crda
      - dbus
      - debconf-utils
      - device-tree-compiler
      - dialog
      - htop
      - initramfs-tools
      - fake-hwclock
      - fping
      - libpam-systemd
      - lsof
      - mmc-utils
      - ncurses-term
      - net-tools
      - netcat-openbsd      -
      - network-manager
      - nocache
      - openssh-server
      - parted
      - psmisc
      - resolvconf
      - rsync
      - ssh
      - sudo
      - sysfsutils
      - sysstat
      - u-boot-tools
      - ucf
      - usbutils
      - wget
      - wireless-regdb
      - wireless-tools
      - *olimex

  lite:
    description: "TODO"
    packages:
      - alsa-utils
      - aptitude
      - automake
      - avahi-autoipd
      - bash-completion
      - bison
      - bridge-utils
      - build-essential
      - command-not-found
      - curl
      - dnsutils
      - dosfstools
      - ethtool
      - evtest
      - expect
      - f2fs-tools
      - f3
      - fbset
      - flex
      - git
      - gnupg2
      - haveged
      - hdparm
      - html2text
      - ifenslave
      - iotop
      - iozone3
      - iperf3
      - iputils-arping
      - libdigest-sha-perl
      - libfuse2
      - libpam-systemd
      - libproc-processtable-perl
      - libssl-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnss-myhostname
      - libwrap0-dev
      - man-db
      - networkd-dispatcher
      - ntfs-3g
      - pciutils
      - pv
      - python3-apt
      - qrencode
      - rfkill
      - screen
      - software-properties-common
      - stress
      - sunxi-tools
      - vim
      - vlan
      - unattended-upgrades
      - unicode-data
      - unzip

  base:
    packages:
      - xserver-xorg
      - xserver-xorg-video-fbdev
      - gvfs-backends
      - gvfs-fuse
      - xfonts-base
      - xinit
      - x11-xserver-utils
      - xfce4
      - lxtask
      - xfce4-terminal
      - thunar-volman
      - gtk2-engines
      - gtk2-engines-murrine
      - gtk2-engines-pixbuf
      - libgtk2.0-bin
      - network-manager-gnome
      - xfce4-notifyd
      - gnome-keyring
      - gcr
      - libgck-1-0
      - p11-kit
      - pasystray
      - pavucontrol
      - pulseaudio
      - pavumeter
      - bluez
      - bluez-tools
      - pulseaudio-module-bluetooth
      - blueman
      - libpam-gnome-keyring
      - libgl1-mesa-dri
      - profile-sync-daemon
      - gnome-orca
      - numix-gtk-theme
      - synaptic
      - apt-xapian-index
      - lightdm
      - lightdm-gtk-greeter
      - galculator
      - hexchat
      - xfce4-screenshooter
      - network-manager-openvpn-gnome
      - mpv
      - fbi
      - cups-pk-helper
      - cups
      - geany
      - atril
      - xarchiver
      - paprefs
      - dbus-x11
      - numix-icon-theme
      - onboard
#      - chromium
      - system-config-printer-common
      - system-config-printer
      - mirage


  full:
    packages:
      - avahi-daemon transmission
      - kazam
      - libreoffice
      - libreoffice-style-tango
      - meld
      - remmina
      - thunderbird




