.olimex: &olimex
    - olinuxino-overlays
    - u-boot-olinuxino
    - u-boot-tools-olinuxino
    - olinuxino-tools

# Release specific packages
releases:
    bullseye:
        minimal:
            - firmware-ralink
            - firmware-realtek
            - firmware-atheros
        base:
            - git
            - avahi-daemon
variants:
    minimal:
        description: "Minimal filesystem"
        packages:
            - alsa-utils
            - bc
            - can-utils
            - cpufrequtils
            - crda
            - debconf-utils
            - device-tree-compiler
            - dialog
            - fake-hwclock
            - gdisk
            - gpiod
            - htop
            - i2c-tools
            - ifupdown
            - initramfs-tools
            - lsof
            - memtool
            - man-db
            - mmc-utils
            - mtd-utils
            - nano
            - ncdu
            - netcat-openbsd
            - net-tools
            - network-manager
            - nocache
            - ntp
            - openssh-server
            - parted
            - psmisc
            - resolvconf
            - rsync
            - screen
            - ssh
            - sudo
            - sysfsutils
            - sysstat
            - tmux
            - tree
            - ucf
            - usbutils
            - wget
            - wireless-regdb
            - wireless-tools
            - *olimex

    base:
        description: "Mainsailos filesystem"
        packages:
            - git
            - nginx
            - virtualenv
            - python3-dev
            - python3-matplotlib
            - libffi-dev
            - build-essential
            - libncurses-dev
            - libusb-dev
            - avrdude
            - gcc-avr
            - binutils-avr
            - avr-libc
            - stm32flash
            - dfu-util
            - libnewlib-arm-none-eabi
            - gcc-arm-none-eabi
            - binutils-arm-none-eabi
            - libusb-1.0-0
            - libusb-1.0-0-dev
            - pkg-config
            - python3-virtualenv
            - python3-libgpiod
            - liblmdb-dev
            - libopenjp2-7
            - libsodium-dev
            - zlib1g-dev
            - libjpeg-dev
            - packagekit
            - wireless-tools
            - curl
            - unzip

    full:
        packages:
            - avahi-daemon
