.olimex: &olimex
  - olinuxino-overlays
  - u-boot-olinuxino

services:
  olimage.core.setup.apt:
    packages:
      - apt-transport-https
      - ca-certificates
      - gnupg

  olimage.core.setup.console:
    packages:
      - console-setup
      - keyboard-configuration

  olimage.core.setup.locales:
    packages:
      - locales

variants:
  minimal:
    description: "Build minimal filesystem"
    packages:
      - bc
      - bzip2
      - chrony
      - cpufrequtils
      - crda
      - dbus
      - debconf-utils
      - device-tree-compiler
      - dialog
      - htop
      - initramfs-tools
      - fake-hwclock
      - fping
      - libpam-systemd
      - lsof
      - mmc-utils
      - ncurses-term
      - net-tools
      - netcat-openbsd      -
      - network-manager
      - nocache
      - openssh-server
      - parted
      - psmisc
      - resolvconf
      - rng-tools
      - rsync
      - ssh
      - sudo
      - sysfsutils
      - sysstat
      - u-boot-tools
      - ucf
      - usbutils
      - wget
      - wireless-regdb
      - wireless-tools
      - *olimex

  lite:
    description: "TODO"
    packages:
      - alsa-utils
      - aptitude
      - automake
      - avahi-autoipd
      - bash-completion
      - bison
      - bridge-utils
      - build-essential
      - command-not-found
      - curl
      - dnsutils
      - dosfstools
      - ethtool
      - evtest
      - expect
      - f2fs-tools
      - f3
      - fbset
      - flex
      - git
      - gnupg2
      - haveged
      - hdparm
      - hostapd
      - html2text
      - ifenslave
      - iotop
      - iozone3
      - iperf3
      - iputils-arping
      - libdigest-sha-perl
      - libfuse2
      - libpam-systemd
      - libproc-processtable-perl
      - libssl-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnss-myhostname
      - libwrap0-dev
      - man-db
      - networkd-dispatcher
      - ntfs-3g
      - pciutils
      - pv
      - python3-apt
      - qrencode
      - rfkill
      - screen
      - software-properties-common
      - stress
      - sunxi-tools
      - vim
      - vlan
      - unattended-upgrades
      - unicode-data
      - unzip

#  lite:
#    description: "Build server-like) filesystem"
#    packages:
#      - apt-listchanges
#      - avahi-daemon
#      - bash-completion
#      - build-essential
#      - ca-certificates
#      - cifs-utils
#      - crda
#      - curl
#      - debconf-utils
#      - dhcpcd5
#      - dosfstools
#      - dphys-swapfile
#      - ed
#      - ethtool
#      - fake-hwclock
#      - fbset
#      - gdb
#      - hardlink
#      - htop
#      - initramfs-tools
#      - less
#      - libfreetype6-dev
#      - libmtp-runtime
#      - lua5.1
#      - luajit
#      - man-db
#      - manpages-dev
#      - ncdu
#      - nfs-common
#      - net-tools
#      - netbase
#      - ntfs-3g
#      - parted
#      - pkg-config
#      - policykit-1
#      - psmisc
#      - python
#      - rsync
#      - ssh
#      - ssh-import-id
#      - strace
#      - sudo
#      - u-boot-tools
#      - unzip
#      - usb-modeswitch
#      - usbutils
#      - v4l-utils
#      - *olimex

#  base:
#    description: "Build base filesystem with X desktop"
#    packages:
##      - apt-xapian-index
#      - *bluetooth
#      - gnome-keyring
#      - gnome-orca
#      - gtk2-engines
#      - gtk2-engines-murrine
#      - gtk2-engines-pixbuf
#      - gvfs-backends
#      - gvfs-fuse
#      - libgck-1-0
#      - libgl1-mesa-dri
#      - libgtk2.0-bin
#      - libpam-gnome-keyring
#      - lightdm
#      - lightdm-gtk-greeter
#      - lxtask
#      - network-manager-gnome
#      - numix-gtk-theme
#      - p11-kit
#      - pasystray
#      - pavucontrol
#      - pavumeter
#      - policykit-1
#      - profile-sync-daemon
#      - pulseaudio
#      - pulseaudio-module-bluetooth
#      - synaptic
#      - thunar-volman
#      - x11-xserver-utils
#      - xfonts-base
#      - xinit
#      - xserver-xorg
#      - xserver-xorg-video-fbdev
#      - *xfce4
#
#
#  full:
#    description: "Build base filesystem with X desktop"
#    packages:
#      - null



