images:
  minimal:
    packages: &minimal
      - 'apt-transport-https'
      - 'bzip2'
      - 'ca-certificates'
      - 'console-setup'
      - 'crda'
      - 'dbus'
      - 'dmsetup'
      - 'gnupg'
      - 'initramfs-tools'
      - 'libpam-systemd'
      - 'locales'
      - 'nano'
      - 'rsync'
      - 'sudo'
      - 'wireless-regdb'

  base:
    packages: &base
      - *minimal

  full:
    packages:
      - *base

