packages:
  minimal: &minimal
    - 'initramfs-tools'
    - 'sudo'

  base: &base
    - *minimal

  full:
    - *base

users:
  root:
    password: '1234'
    force_change: yes

  olimex:
    password: 'olimex'

