partitions:
  boot:
    fstab:
      type: 'ext4'
      mount: '/boot'
      options: 'defaults'
      dump: 0
      passno: 2
    parted:
      type: 'ext4'
      start: '4MiB'
      end: '100MiB'

  rootfs:
    fstab:
      type: 'ext4'
      mount: '/'
      options: 'defaults,noatime,nodiratime,commit=600,errors=remount-ro'
      dump: 0
      passno: 1
    parted:
      type: 'ext4'
      start: '100MiB'
      end: '100%'