users:
  root:
    password: 'olimex'
#    permit_login: yes
#    force_change: yes

  olimex:
    password: 'olimex'
    groups: [ 'adm', 'audio', 'cdrom', 'dialout', 'games', 'netdev', 'plugdev', 'sudo', 'video', 'users' ]
