users:
    root:
        password: "olimex"
    #    permit_login: yes
    #    force_change: yes

    um:
        password: "um"
        groups:
            [
                "adm",
                "audio",
                "cdrom",
                "dialout",
                "games",
                "netdev",
                "plugdev",
                "sudo",
                "video",
                "users",
                "tty",
            ]
