name: Build UltimainsailOS
on:
  push:
    branches:
      - "develop"

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          apt-get update
          apt-get install --yes qemu-user-static

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: DEBUG
        shell: bash
        run: |
          ls -al
