name: Build UltimainsailOS
on:
  push:
    branches:
      - "develop"
    paths-ignore:
      - ".github/workflows/olimage.yml"

  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-buildtrain-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install --yes qemu-user-static

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ultimainsailos

      - name: Build Image
        shell: bash
        run: |
          cd ultimainsailos
          ls -al
          chmod +x *.sh
          ./build-a20.sh

      - name: DEBUG - Show output
        shell: bash
        run: |
          cd ultimainsailos/output/a20-olinuxino/images
          ls -al

      - name: Compress Image
        shell: bash
        run: |
          CPU_COUNT="$(nproc)"
          echo -e "\e[32mUsing ${CPU_COUNT} Cores for compression...\e[0m"
          xz -efkvz9T"${CPU_COUNT}" A20-OLinuXino-bullseye-minimal*.img || true

      - name: DEBUG - Show compressed images
        shell: bash
        run: |
          cd ultimainsailos/output/a20-olinuxino/images
          ls -al
