name: Build UltimainsailOS
on:
  push:
    branches:
      - "develop"

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
