name: Show olimage help
on:
  workflow_dispatch:

jobs:
  olimage-help:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
        debootstrap \
        gdisk \
        kpartx \
        parted \
        python-dev \
        python3 \
        python3-gdbm \
        python3-pip \
        python3-tk \
        python3-cerberus \
        python3-click \
        python3-jinja2 \
        python3-yaml \
        python3-cliapp \
        rsync \
        qemu-user-static \
        qemu-utils \
        u-boot-tools \
        udev


      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ultimainsailos

      - name: Show Help
        shell: bash
        run: |
          cd ultimainsailos
          pip3 install halo pinject cerberus
          python3 -m olimage --help
